FROM i386/debian:sid

RUN echo "deb-src http://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install build-essential --yes
RUN apt-get build-dep wine --yes
RUN apt-get install vim --yes
